### ISSUE TITLE
Can I receive intel update on windows ?

### ISSUE THREAD

**Issue by Azaretdodo** [intel/Intel-Linux-Processor-Microcode-Data-Files#11]
Hello I have git clone your fork on my windows setup,

How to receive intel microcode update on It setup after just put your fork at the root of my HDD ?

Thank you in advance to answer my question,

Regards.

Azaretdodo.

**Comment by mcu-administrator** [comment]
@Azaretdodo - Thanks for your question.  If you are looking to apply MCUs via the Windows operating system, you will need to obtain the latest updates via Microsoft's Windows Update.  There are a number of catalog updates available currently.  Which version will depend upon which OS version and which CPU you are needing to update.  The MCUs included in this Github are formatted for updating the Linux operating system only.

**Comment by Azaretdodo** [comment]
OK thank you for your answer

I think if they are update on Windows It will go at the good time?

I have installed It fork on my Linux server there is some months what is the last time where a Intel microcode was deploy?

Thank you for your time bring to secure the community,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by mcu-administrator** [comment]
@Azaretdodo the latest release is available here:  https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20190618 

For Windows, you can look here for a list of currently available updates and how they can be obtained:  https://support.microsoft.com/en-us/help/4093836/summary-of-intel-microcode-updates.

**Comment by Azaretdodo** [comment]
Thank you

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : MCU Administrator <notifications@github.com>
Envoyé : Tuesday, September 10, 2019 5:35:55 PM
À : intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)


@Azaretdodo<https://github.com/Azaretdodo> the latest release is available here: https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20190618

For Windows, you can look here for a list of currently available updates and how they can be obtained: https://support.microsoft.com/en-us/help/4093836/summary-of-intel-microcode-updates.

**Comment by Azaretdodo** [comment]
I am back !,


**I went to install wsl2 which my own python module sphinx (always on my windows setup) then I enable wsl1 and VM capabilities which powershell then I have installed ubuntu 18.04 (I don't know why but It is a server version) finaly I have put our github on the ubuntu 18.04 ;)**

Do I will receive an update now for my windows setup ?

Thank you in advance to explained if yes or no,

Regards.


AZaretdodo.

**Comment by JacobWKlein** [comment]
To update Intel Microcode in Windows:

I use the "VMware CPU Microcode Update Driver" Fling:
[https://labs.vmware.com/flings/vmware-cpu-microcode-update-driver](https://labs.vmware.com/flings/vmware-cpu-microcode-update-driver)

I made some instructions here:
[https://1drv.ms/t/s!AgP0NBEuAPQRp6BviVXfMvoDNOTMaQ](https://1drv.ms/t/s!AgP0NBEuAPQRp6BviVXfMvoDNOTMaQ)

Good luck!

**Comment by Azaretdodo** [comment]
Hello,


Can I update because my VM isn't a vmware VM?

I will try your advice,

Have a nice day from France,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Azaretdodo** [comment]
Hello Jacob,


From VMWare link I don’t have dat file,

I don’t know why but the inf file can’t be install from the hardware information windows setup…

The uninstall bat works but the install bat doesn’t works,

Too from the programs you advice I don’t find for update driver…

Can you help me ?

Thank you in advance,


Azaretdodo.

De : JacobWKlein <notifications@github.com>
Envoyé : dimanche 29 septembre 2019 21:48
À : intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)


To update Intel Microcode in Windows:

I use the "VMware CPU Microcode Update Driver" Fling:
https://labs.vmware.com/flings/vmware-cpu-microcode-update-driver

I made some instructions here:
https://1drv.ms/t/s!AgP0NBEuAPQRp6BviVXfMvoDNOTMaQ

Good luck!

**Comment by JacobWKlein** [comment]
You need the microcode.dat file, which is in the "My output" folder in the 3rd link, as I described. Also, this fling runs directly in your native Windows desktop installation, does not need to run inside of a VM.

**Comment by Azaretdodo** [comment]
From you I have received only two link as Following received :

To update Intel Microcode in Windows:

I use the "VMware CPU Microcode Update Driver" Fling:
https://labs.vmware.com/flings/vmware-cpu-microcode-update-driver

I made some instructions here:
https://1drv.ms/t/s!AgP0NBEuAPQRp6BviVXfMvoDNOTMaQ

Good luck!


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : JacobWKlein <notifications@github.com>
Envoyé : Monday, September 30, 2019 2:33:31 PM
À : intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)


You need the microcode.dat file, which is in the "My output" folder in the 3rd link, as I described. Also, this fling runs directly in your native Windows desktop installation, does not need to run inside of a VM.

**Comment by JacobWKlein** [comment]
Try refreshing the page, or clearing your cache then refreshing the page. I edited the post hours ago. And please stop quoting everything unnecessarily.

**Comment by JacobWKlein** [comment]
In order to see the edited posts, visit this thread on github.com instead of just looking at your email inbox. Also, while you're looking at the thread on the site, consider removing the quoted material from your posts, to consolidate the responses.

**Comment by Azaretdodo** [comment]
I am in download yours input and output forlders then I will use your program converting for install all updates 😊

Now I will go to workout if you have advice I will heard your advice or advices…

I will use your program converting after the workout finaly if you have suggesting I will heard you !

Have a nice day from France !

Regards.


Azaretdodo.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : JacobWKlein <notifications@github.com>
Envoyé : Monday, September 30, 2019 3:16:05 PM
À : intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)


In order to see the edited posts, visit this thread on github.com instead of just looking at your email inbox. Also, while you're looking at the thread on the site, consider removing the quoted material from your posts, to consolidate the responses.

**Comment by Azaretdodo** [comment]
Hello Jacob,


I have converted all microcodes but I don’t know how to install thoses microcodes cpu updates…

Thank you in advance to explain how to install thoses updates,

Regards.


Dorian ROSSE.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Dorian ROSSE
Envoyé : Monday, September 30, 2019 3:27:21 PM
À : intel/Intel-Linux-Processor-Microcode-Data-Files <reply@reply.github.com>; intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Mention <mention@noreply.github.com>
Objet : RE : [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)

I am in download yours input and output forlders then I will use your program converting for install all updates 😊

Now I will go to workout if you have advice I will heard your advice or advices…

I will use your program converting after the workout finaly if you have suggesting I will heard you !

Have a nice day from France !

Regards.


Azaretdodo.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : JacobWKlein <notifications@github.com>
Envoyé : Monday, September 30, 2019 3:16:05 PM
À : intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)


In order to see the edited posts, visit this thread on github.com instead of just looking at your email inbox. Also, while you're looking at the thread on the site, consider removing the quoted material from your posts, to consolidate the responses.

**Comment by Azaretdodo** [comment]
I have all installed with error code 0

What must I do now?

Thank you in advance,

Regards.


Dorian rosse.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by JacobWKlein** [comment]
In the install instructions, the final step is:
Verify the updated Microcode version

HWiNFO64 will show you the version you are currently using. If it shows the version you expect, even after rebooting the PC, then the installation of the updated microcode is complete.

![image](https://user-images.githubusercontent.com/13267799/65902058-7be1da80-e387-11e9-8ef6-80084612a87a.png)

**Comment by Azaretdodo** [comment]
My laster should be June or August because September wasn't build for my cpu,

how to know the version number of this microcode version?

Thank you in advance for this laster question,

Regards.


Dorian rosse.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by JacobWKlein** [comment]
Determining which microcode is available, involves a bit of work, so be prepared to do the work. Also, there are probably many ways to do it, so I'll just give my recommended (easiest?) way, along with examples for my 6 PCs.

1) To find your CPUID:
Run "Inspectre", and note the CPUID it gives.
My 6 PCs, I have: 306F2, 806EC, 106A4, 106E5, 20655, 306D4

2) To find the microcode version and date, that is inside any Intel Release:
Search the microcode.dat file (created from the Intel release), for the CPUID, to find what looks like a "header line" for that CPUID. In that header line, you'll see the microcode version #, and a microcode date. Examples for my 6 PCs, below. Note: Some possibly fun info about the header can be found here: [https://blog.fpmurphy.com/2016/12/python-3-utilities-for-parsing-intel-microcode.html](https://blog.fpmurphy.com/2016/12/python-3-utilities-for-parsing-intel-microcode.html)

3) To find newer/older microcode releases at the [platomav repository](https://github.com/platomav/CPUMicrocodes):
Search the Intel folder for files that have the CPUID in their name, to find a file that looks like it should match. The version number and microcode date, are also in the file name. You can download those platomav files, use my converter executable to create a microcode.dat file from them, then use that in the fling. You can click the file in GitHub, to view its history, to find the older versions of the microcodes, if desired. Examples for my 6 PCs, below. Note: Sometimes the same CPUID will exist for multiple platforms, and I do not know the easiest way to find out what platform your CPU is.

I'll update my instructions text file with these new instructions, too. Thanks for prompting me.

Good luck!

---------------
For my 6 PCs, here are the headers using my microcode.dat file generated from the 20190918 Intel Release:

306F2:
0x00000001,	0x00000043,	0x03012019,	0x000306f2,
Microcode version 43, released 3/1/2019

806EC:
0x00000001,	0x000000b8,	0x03302019,	0x000806ec,
Microcode version B8, released 3/30/2019

106A4:
0x00000001,	0x00000012,	0x06212013,	0x000106a4,
Microcode version 12, released 6/21/2013

106E5:
0x00000001,	0x0000000a,	0x05082018,	0x000106e5,
Microcode version A, released 5/8/2018

20655:
0x00000001,	0x00000007,	0x04232018,	0x00020655,
Microcode version 7, released 4/23/2018

306D4:
0x00000001,	0x0000002e,	0x06132019,	0x000306d4,
Microcode version 2E, released 6/13/2019

---------------
For my 6 PCs, here are the platomav repository files that are the latest versions:

306F2:
cpu306F2_plat6F_ver00000043_2019-03-01_PRD_6413577D.bin
Microcode version 43, released 3/1/2019

806EC:
cpu806EC_plat94_ver000000C6_2019-08-14_PRD_F8A49D59.bin
Microcode version C6, released 8/14/2019

106A4:
cpu106A4_plat03_ver00000013_2015-06-30_PRD_35DDB232.bin
Microcode version 13, released 6/30/2015

106E5:
cpu106E5_plat13_ver0000000A_2018-05-08_PRD_B16FCEEB.bin
Microcode version A, released 5/8/2018

20655:
cpu20655_plat92_ver00000007_2018-04-23_PRD_8B585C97.bin
Microcode version 7, released 4/23/2018

306D4:
cpu306D4_platC0_ver0000002E_2019-06-13_PRD_88B9395D.bin
Microcode version 2E, released 6/13/2019

---------------

**Comment by Azaretdodo** [comment]
Thank you for your e-mail when I will have the time I will be able to check on my setup,

Too for fork where there is a db extension file I will try to put the database in kubernete or / and containerd by search on Google,

Thank you for all time you do for me,

Have a nice day,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Azaretdodo** [comment]
Sorry but where I should find « inspectre » ?

De : JacobWKlein <notifications@github.com>
Envoyé : mardi 1 octobre 2019 15:03
À : intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)


Determining which microcode is available, involves a bit of work, so be prepared to do the work. Also, there are probably many ways to do it, so I'll just give my recommended (easiest?) way, along with examples for my 6 PCs.

  1.  To find your CPUID:
Run "Inspectre", and note the CPUID it gives.
My 6 PCs, I have: 306F2, 806EC, 106A4, 106E5, 20655, 306D4
  2.  To find the microcode version and date, that is inside any Intel Release:
Search the microcode.dat file (created from the Intel release), for the CPUID, to find what looks like a "header line" for that CPUID. In that header line, you'll see the microcode version #, and a microcode date. Examples for my 6 PCs, below. Note: Some possibly fun info about the header can be found here: https://blog.fpmurphy.com/2016/12/python-3-utilities-for-parsing-intel-microcode.html
  3.  To find newer/older microcode releases at the platomav repository<https://github.com/platomav/CPUMicrocodes>:
Search the Intel folder for files that have the CPUID in their name, to find a file that looks like it should match. The version number and microcode date, are also in the file name. You can download those platomav files, use my converter executable to create a microcode.dat file from them, then use that in the fling. You can click the file in GitHub, to view its history, to find the older versions of the microcodes, if desired. Examples for my 6 PCs, below. Note: Sometimes the same CPUID will exist for multiple platforms, and I do not know the easiest way to find out what platform your CPU is.

I'll update my instructions text file with these new instructions, too. Thanks for prompting me.

Good luck!

________________________________

For my 6 PCs, here are the headers using my microcode.dat file generated from the 20190918 Intel Release:

306F2:
0x00000001, 0x00000043, 0x03012019, 0x000306f2,
Microcode version 43, released 3/1/2019

806EC:
0x00000001, 0x000000b8, 0x03302019, 0x000806ec,
Microcode version B8, released 3/30/2019

106A4:
0x00000001, 0x00000012, 0x06212013, 0x000106a4,
Microcode version 12, released 6/21/2013

106E5:
0x00000001, 0x0000000a, 0x05082018, 0x000106e5,
Microcode version A, released 5/8/2018

20655:
0x00000001, 0x00000007, 0x04232018, 0x00020655,
Microcode version 7, released 4/23/2018

306D4:
0x00000001, 0x0000002e, 0x06132019, 0x000306d4,
Microcode version 2E, released 6/13/2019

________________________________

For my 6 PCs, here are the platomav repository files that are the latest versions:

306F2:
cpu306F2_plat6F_ver00000043_2019-03-01_PRD_6413577D.bin
Microcode version 43, released 3/1/2019

806EC:
cpu806EC_plat94_ver000000C6_2019-08-14_PRD_F8A49D59.bin
Microcode version C6, released 8/14/2019

106A4:
cpu106A4_plat03_ver00000013_2015-06-30_PRD_35DDB232.bin
Microcode version 13, released 6/30/2015

106E5:
cpu106E5_plat13_ver0000000A_2018-05-08_PRD_B16FCEEB.bin
Microcode version A, released 5/8/2018

20655:
cpu20655_plat92_ver00000007_2018-04-23_PRD_8B585C97.bin
Microcode version 7, released 4/23/2018

306D4:
cpu306D4_platC0_ver0000002E_2019-06-13_PRD_88B9395D.bin
Microcode version 2E, released 6/13/2019

________________________________

**Comment by Azaretdodo** [comment]
OK I went to google serach inspectre for find 😊

De : JacobWKlein <notifications@github.com>
Envoyé : mardi 1 octobre 2019 15:03
À : intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)


Determining which microcode is available, involves a bit of work, so be prepared to do the work. Also, there are probably many ways to do it, so I'll just give my recommended (easiest?) way, along with examples for my 6 PCs.

  1.  To find your CPUID:
Run "Inspectre", and note the CPUID it gives.
My 6 PCs, I have: 306F2, 806EC, 106A4, 106E5, 20655, 306D4
  2.  To find the microcode version and date, that is inside any Intel Release:
Search the microcode.dat file (created from the Intel release), for the CPUID, to find what looks like a "header line" for that CPUID. In that header line, you'll see the microcode version #, and a microcode date. Examples for my 6 PCs, below. Note: Some possibly fun info about the header can be found here: https://blog.fpmurphy.com/2016/12/python-3-utilities-for-parsing-intel-microcode.html
  3.  To find newer/older microcode releases at the platomav repository<https://github.com/platomav/CPUMicrocodes>:
Search the Intel folder for files that have the CPUID in their name, to find a file that looks like it should match. The version number and microcode date, are also in the file name. You can download those platomav files, use my converter executable to create a microcode.dat file from them, then use that in the fling. You can click the file in GitHub, to view its history, to find the older versions of the microcodes, if desired. Examples for my 6 PCs, below. Note: Sometimes the same CPUID will exist for multiple platforms, and I do not know the easiest way to find out what platform your CPU is.

I'll update my instructions text file with these new instructions, too. Thanks for prompting me.

Good luck!

________________________________

For my 6 PCs, here are the headers using my microcode.dat file generated from the 20190918 Intel Release:

306F2:
0x00000001, 0x00000043, 0x03012019, 0x000306f2,
Microcode version 43, released 3/1/2019

806EC:
0x00000001, 0x000000b8, 0x03302019, 0x000806ec,
Microcode version B8, released 3/30/2019

106A4:
0x00000001, 0x00000012, 0x06212013, 0x000106a4,
Microcode version 12, released 6/21/2013

106E5:
0x00000001, 0x0000000a, 0x05082018, 0x000106e5,
Microcode version A, released 5/8/2018

20655:
0x00000001, 0x00000007, 0x04232018, 0x00020655,
Microcode version 7, released 4/23/2018

306D4:
0x00000001, 0x0000002e, 0x06132019, 0x000306d4,
Microcode version 2E, released 6/13/2019

________________________________

For my 6 PCs, here are the platomav repository files that are the latest versions:

306F2:
cpu306F2_plat6F_ver00000043_2019-03-01_PRD_6413577D.bin
Microcode version 43, released 3/1/2019

806EC:
cpu806EC_plat94_ver000000C6_2019-08-14_PRD_F8A49D59.bin
Microcode version C6, released 8/14/2019

106A4:
cpu106A4_plat03_ver00000013_2015-06-30_PRD_35DDB232.bin
Microcode version 13, released 6/30/2015

106E5:
cpu106E5_plat13_ver0000000A_2018-05-08_PRD_B16FCEEB.bin
Microcode version A, released 5/8/2018

20655:
cpu20655_plat92_ver00000007_2018-04-23_PRD_8B585C97.bin
Microcode version 7, released 4/23/2018

306D4:
cpu306D4_platC0_ver0000002E_2019-06-13_PRD_88B9395D.bin
Microcode version 2E, released 6/13/2019

________________________________

**Comment by Azaretdodo** [comment]
It show I can install microcode update but Should It show if It miss any or some microcode update(s) ?

De : JacobWKlein <notifications@github.com>
Envoyé : mardi 1 octobre 2019 15:03
À : intel/Intel-Linux-Processor-Microcode-Data-Files <Intel-Linux-Processor-Microcode-Data-Files@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [intel/Intel-Linux-Processor-Microcode-Data-Files] Can I receive intel update on windows ? (#11)


Determining which microcode is available, involves a bit of work, so be prepared to do the work. Also, there are probably many ways to do it, so I'll just give my recommended (easiest?) way, along with examples for my 6 PCs.

  1.  To find your CPUID:
Run "Inspectre", and note the CPUID it gives.
My 6 PCs, I have: 306F2, 806EC, 106A4, 106E5, 20655, 306D4
  2.  To find the microcode version and date, that is inside any Intel Release:
Search the microcode.dat file (created from the Intel release), for the CPUID, to find what looks like a "header line" for that CPUID. In that header line, you'll see the microcode version #, and a microcode date. Examples for my 6 PCs, below. Note: Some possibly fun info about the header can be found here: https://blog.fpmurphy.com/2016/12/python-3-utilities-for-parsing-intel-microcode.html
  3.  To find newer/older microcode releases at the platomav repository<https://github.com/platomav/CPUMicrocodes>:
Search the Intel folder for files that have the CPUID in their name, to find a file that looks like it should match. The version number and microcode date, are also in the file name. You can download those platomav files, use my converter executable to create a microcode.dat file from them, then use that in the fling. You can click the file in GitHub, to view its history, to find the older versions of the microcodes, if desired. Examples for my 6 PCs, below. Note: Sometimes the same CPUID will exist for multiple platforms, and I do not know the easiest way to find out what platform your CPU is.

I'll update my instructions text file with these new instructions, too. Thanks for prompting me.

Good luck!

________________________________

For my 6 PCs, here are the headers using my microcode.dat file generated from the 20190918 Intel Release:

306F2:
0x00000001, 0x00000043, 0x03012019, 0x000306f2,
Microcode version 43, released 3/1/2019

806EC:
0x00000001, 0x000000b8, 0x03302019, 0x000806ec,
Microcode version B8, released 3/30/2019

106A4:
0x00000001, 0x00000012, 0x06212013, 0x000106a4,
Microcode version 12, released 6/21/2013

106E5:
0x00000001, 0x0000000a, 0x05082018, 0x000106e5,
Microcode version A, released 5/8/2018

20655:
0x00000001, 0x00000007, 0x04232018, 0x00020655,
Microcode version 7, released 4/23/2018

306D4:
0x00000001, 0x0000002e, 0x06132019, 0x000306d4,
Microcode version 2E, released 6/13/2019

________________________________

For my 6 PCs, here are the platomav repository files that are the latest versions:

306F2:
cpu306F2_plat6F_ver00000043_2019-03-01_PRD_6413577D.bin
Microcode version 43, released 3/1/2019

806EC:
cpu806EC_plat94_ver000000C6_2019-08-14_PRD_F8A49D59.bin
Microcode version C6, released 8/14/2019

106A4:
cpu106A4_plat03_ver00000013_2015-06-30_PRD_35DDB232.bin
Microcode version 13, released 6/30/2015

106E5:
cpu106E5_plat13_ver0000000A_2018-05-08_PRD_B16FCEEB.bin
Microcode version A, released 5/8/2018

20655:
cpu20655_plat92_ver00000007_2018-04-23_PRD_8B585C97.bin
Microcode version 7, released 4/23/2018

306D4:
cpu306D4_platC0_ver0000002E_2019-06-13_PRD_88B9395D.bin
Microcode version 2E, released 6/13/2019

________________________________
