### ISSUE TITLE
Spec updates links in releasenote file

### ISSUE THREAD

**Issue by kerolasa** [intel/Intel-Linux-Processor-Microcode-Data-Files#13]
When new updates are added it would be really nice to see in releasenote file links to related specification update documents, such as: https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/xeon-scalable-spec-update.pdf

**Comment by mcu-administrator** [comment]
Currently, we are maintaining the format of the releasenote file for legacy purposes.  However, we will now also generate a release from Github and the announcement has a link to the [Intel Resource & Design Center](https://www.intel.com/content/www/us/en/design/resource-design-center.html) where you can find the Specification Update documents.

**Comment by kerolasa** [comment]
Maybe I was unclear with the request. It would be great if the commit would contain direct links to spec updates so that it would be simple to see what changed even without signup. As this information is clearly public I don't see any harm in making information to easy to find.

Sure enough making more complete / useful release notes will require effort. I think it's better if one person will collect all the update references together rather than everyone who is interested separately. That's really how I see what this request boils down to.

**Comment by mcu-administrator** [comment]
Release note format has been updated to include links to Specification Updates for products being updated including for past releases.
