### ISSUE TITLE
06-9e-0c removed from 20191112

### ISSUE THREAD

**Issue by limetech** [intel/Intel-Linux-Processor-Microcode-Data-Files#19]
Was this intentional?

**Comment by mcu-administrator** [comment]
Yes.  This particular stepping was not released to production.

**Comment by hmh** [comment]
A google search shows several users with:

"Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (family: 0x6, model: 0x9e, stepping: 0xc)"

A few look like posts and artifacts from developers that might be working in hardware enablement (reports from such developers using early-release rigs with QS processors are to be expected).

But some of the search results do look like forum posts from enthusiast end-users, etc.

**Comment by esyr-rh** [comment]
There are quite a few models listed in the Update Guidance for SA-00270[1]:

Intel® CoreTM Processor i9-9980HK, 9880H
Intel® CoreTM Processor i7-9850H, 9750HF
Intel® CoreTM Processor i5-9400H, 9300H
Intel® CoreTM Processor i9-9900K, i9-9900KF
Intel® CoreTM Processor i7-9700K, i7-9700KF
Intel® CoreTM Processor i5-9600K, i5-9600KF, i5-9400, i5-9400F

And one can grab the 0xc6 revision of the microcode (mentioned in the Update Guidance) at [2], for example:

`$ iucode_tool -L cpu906EC_plat22_ver000000C6_2019-08-14_PRD_177C8996.bin `
`microcode bundle 1: cpu906EC_plat22_ver000000C6_2019-08-14_PRD_177C8996.bin`
`  001/001: sig 0x000906ec, pf_mask 0x22, 2019-08-14, rev 0x00c6, size 99328`

But all that just adds work for distribution maintainers.

[1] https://www.intel.com/content/dam/www/public/us/en/documents/corporate-information/SA00270-microcode-update-guidance.pdf
[2] https://github.com/platomav/CPUMicrocodes/blob/master/Intel/cpu906EC_plat22_ver000000C6_2019-08-14_PRD_177C8996.bin

**Comment by mcu-administrator** [comment]
This is under investigation.  We'll update as soon as we have an answer.

**Comment by mcu-administrator** [comment]
This has been resolved with [microcode-20191113](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20191113).

**Comment by esyr-rh** [comment]
Thank you!
