### ISSUE TITLE
Westmere

### ISSUE THREAD

**Issue by kev009** [intel/Intel-Linux-Processor-Microcode-Data-Files#2]
I have some Westmere  (Xeon 5600 series) servers.  Are they now a pile of garbage, or is there some combination of kernel patch, and/or disabling HT, that is sufficient for protection of the MDS hardware snafu?

**Comment by hotaru2k3** [comment]
https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/MDS

> **IMPORTANT:** There is no software fallback mechanism available for processors that have not received microcode updates from Intel. Mitigation is only possible if Intel has provided a microcode update for your processor.
