### ISSUE TITLE
Can't access RAM from PCIe

### ISSUE THREAD

**Issue by ranshalit** [intel/Intel-Linux-Processor-Microcode-Data-Files#22]
Hello,

Is there an known issue of access Xeon's RAM from PCIe (DMA access) ? We observe the issue when using linux 4.x on E5 servers ?
We have this issue only with Xeon E5 + Linux, and using other Intel's chip there is no issue.
When we use the same BIOS, Chip, with windows , we manage to access RAM's from PCIe (DMA access).

I've tried to search and asked the question, but got no response.
Is it a known issue in this chip ? Why is it observed with Linux , but not with Windows ? 
**Should I upgrade BIOS or is it some BIOS parameter that I should configure ?**

We also tried to get assistance from Intel's and from Linux kernel, but nothing helped understanding this issue.
https://bugzilla.kernel.org/show_bug.cgi?id=205701

Any suggestion bout this issue will help,

Ran

**Comment by hmh** [comment]
I don't think this is the correct place to ask about this.  Maybe the Intel developer forums?

**Comment by ranshalit** [comment]
I tried the developer zone, but got no response.
Is it a microcode issue ?
