### ISSUE TITLE
Readme.md missing

### ISSUE THREAD

**Issue by manuel-91** [intel/Intel-Linux-Processor-Microcode-Data-Files#26]
If there is anyone who knows a little what this project is doing please write a few sentences.
* What is this repo doing?
* Why shoud I use this package?

If [the archlinux description for microcode](https://wiki.archlinux.org/index.php/Microcode) describes this well, then a reference might be helpful.

**Comment by projach** [comment]
https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00233.html

**Comment by mcu-administrator** [comment]
New readme.md format included with microcode-20201110 tag
