### ISSUE TITLE
06-3c-03 not updated as part of 20200609 Release

### ISSUE THREAD

**Issue by ryao** [intel/Intel-Linux-Processor-Microcode-Data-Files#32]
The git history claims that the file has changed, but my local sha256 is 2af41bcbe3412aec07c720e2be6ebdd092adaf8a7635efef6c5480a0b53a185d, which is identical to the version from the 20200508 release.

iucode_tool reports it as `sig 0x000306c3, pf_mask 0x32, 2019-11-12, rev 0x0028, size 23552`. An Intel Xeon E5-1650 v3 running Linux 5.7.2 was found to fail to report "SRBDS: Mitigation: Microcode" in dmesg.

**Comment by ryao** [comment]
I see the problem. I thought I got the latest microcode, but I hadn't. The version codes were so similar that my eyes got mixed up. It is not clear to me why toralf did not see the mitigation enabled on his machine, but I am going to close this until I know for certain there is something that needs to be done by Intel.

**Comment by ryao** [comment]
Actually, wait... I just realized that even though my local copy is really the 20200601 version, the 20200609 release had the same checksum as the 20200601 version, so there is no point in closing this. There is something actionable here. Namely, we need new microcode.

**Comment by andyhhp** [comment]
I concur with @esyr-rh .  There was a microcode update in this drop, as compared to May 20th, and the versions/shasums match.

2020-06-01 isn't a drop from here.  However, it is likely that whomever packaged that drop did get the up-to-date Haswell E3 microcode, seeing how long its been available to OEMs for.

Xeon E3's and E5's don't use the same microcode.  E5's use 06-3f-02 or 06-3f-04, E3's use this one.

Xeon E5's are not affected by SRBDS.  There is no change the RDRAND/RDSEED instructions in microcode, and the sysfs file ought to read "not vulnerable".

If you want to test your E3 without installing a new kernel, install the msr-tools package, and `modprobe msr; rdmsr 0x123`.  If you've got updated microcode, you should see 0 or 1 returned.  If you've on older microcode, you should see an error trying to read that.

**Comment by ryao** [comment]
@andyhhp Thanks for helping to clear up the confusion.
