### ISSUE TITLE
need microcode for  intel i5 7200u 

### ISSUE THREAD

**Issue by RAJU2529** [intel/Intel-Linux-Processor-Microcode-Data-Files#37]
i am using Asus  vivobook 15 x542uq laptop with intel  i5 7200u , currently  B4 microcode is installed in bios firmware, i need latest microcode update for issue intel SA-00320.  
![cpu](https://user-images.githubusercontent.com/3296790/85170561-305fbb80-b28b-11ea-82e5-9214daf860e1.JPG)

**Comment by esyr-rh** [comment]
https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/raw/main/intel-ucode/06-8e-09

**Comment by RAJU2529** [comment]
@esyr-rh . Thanks
