### ISSUE TITLE
Model 06-4f-01 microcode files

### ISSUE THREAD

**Issue by nivedita76** [intel/Intel-Linux-Processor-Microcode-Data-Files#40]
Can the file for this model now be moved out of intel-ucode-with-caveats?

My understanding of the history is that this was done originally because of issues with microcode revisions prior to b000021, due to erratum BDX90:

> Loading Microcode Updates or Executing an Authenticated Code Module May Result in a System Hang
> An uncorrectable error (IA32_MC3_STATUS.MCACOD=0400 and IA32_MC3_STATUS.MSCOD=0080) may be logged for processors that have more than 2.5MB last-level-cache per core on attempting to load a microcode update or execute an authenticated code module. This issue does not occur with microcode updates with a signature of 0x0b000021 and greater.
Due to this erratum, the processor may hang when attempting to load a microcode update or execute an authenticated code module.

The microcode version is now at b000038, which doesn't have issues AFAIK.

**Comment by andyhhp** [comment]
BDX90 relates to the current version of microcode when you attempt a patch load.  Not the version of the patch you're trying to update to.

It will be "with caveats" until someone can prove that every Broadwell-X system in the world has had a firmware update which includes b000021 or later, or that every piece of OS software has a safety check or workaround for BDX90.  (Neither are plausible scenarios.)

**Comment by nivedita76** [comment]
Aah, thanks. I interpreted the language in that erratum to mean the version of the update rather than the current microcode on the cpu.
