### ISSUE TITLE
Microcode 0x38 for 06-5c-09 causes hard lockups

### ISSUE THREAD

**Issue by TID41** [intel/Intel-Linux-Processor-Microcode-Data-Files#42]
Months ago, my Acer Swift SF113-31-P5CK laptop (running Kubuntu and KDE Neon; the issue happened with both, and also with non-Ubuntu distros Fedora and OpenSUSE that I tried on it) began to hard lock at seemingly random intervals, ignoring sysrq+REISUB and requiring a force-off. After some trial and error, I tried removing the pertinent microcode file (06-5c-09, 0x38) from /lib/firmware/intel-ucode and updating the initramfs, reverting to the version in the system firmware, and the lockup never happened again. After I discovered that, I checked, and indeed, the onset of the lockups coincided with the delivery of the latest Intel microcode by Ubuntu.

I then tried inserting the second newest microcode file, 0x32, into /lib/firmware/intel-ucode and updating the initramfs, and again, no lockups. They previously happened anywhere from 5 minutes to a few hours into a session, and often multiple times a day. They happened particularly quickly when using Zoom, which I've used (with privacy caveats in mind) recently for reasons that are probably self-evident.

By now it has been several months since the last lockup, and I use the laptop hours each day. It's been completely stable since getting rid of 0x38.

**Comment by esyr-rh** [comment]
Does update to revision 0x40, that comes with microcode-20201110 release, help?

**Comment by TID41** [comment]
On 11/10/2020 11:55 PM, esyr-rh wrote:
 > Does update to revision 0x40, that comes with microcode-20201110
 > release, help?

I tried to put in a reply on GitHub, and it tells me "you cannot comment 
at this time." Fantastic!

I did install the new microcode package yesterday morning (it's evening 
now where I am), and I verified that it was loading (early) via dmesg, 
and it's been stable so far. I'll report back when more time has elapsed 
and I know more. I use the laptop daily anyway, so it will get a lot of 
hours of testing!

**Comment by TID41** [comment]
It has been two weeks or so since I installed 0x40 on the Swift, and 
there have been no lockups. It looks as if the problem is fixed, as I 
would expect to have seen several lockups by now. I'll certainly report 
back immediately if it locks up, or after a while if it hasn't to 
confirm that I am still watching it, as long as the issue is still open.

**Comment by whpenner** [comment]
Is this issue resolved?

**Comment by TID41** [comment]
Yes, it is resolved. It has not locked up since the update to 0x40.
