### ISSUE TITLE
intel-microcode (intel-microcode 3.20200609.0ubuntu0.20.04.2) is not working with core i9 (0xcc)

### ISSUE THREAD

**Issue by dimadeush** [intel/Intel-Linux-Processor-Microcode-Data-Files#50]
When using latest ubuntu LTS I can see black screen. Latest working version 3.20191115.1ubuntu3. Please fix the bug.

`
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
stepping        : 13
microcode       : 0xcc
cpu MHz         : 1099.662
cache size      : 16384 KB
physical id     : 0
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 15
initial apicid  : 15
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs taa itlb_multihit srbds
bogomips        : 4800.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

(END)
`

Please find all info here https://bugs.launchpad.net/ubuntu/+source/intel-microcode/+bug/1911893 and here https://forums.linuxmint.com/viewtopic.php?f=49&t=339625&sid=bdf869985cc73de93fc77e1ce330aa29

**Comment by dimadeush** [comment]
Hello

Do we have any updated?  Please help, I wanna use my core i9 with latest intel microcode :)

With hope
Thanks in Advance

**Comment by dimadeush** [comment]
Hello

Just need to know if somebody still support intel microcode and if somebody working on this issue now.

Thanks in Advance

**Comment by whpenner** [comment]
MCU revision 0xcc is pretty old and an issue was resolved quite some time ago.  Try updating to the last microcode update and let me know if you continue to see the issue.

**Comment by dimadeush** [comment]
No, it is not working. the same issue as in the past. It is a pity.  Can you check once again and fix the issue?

**Comment by dimadeush** [comment]
@whpenner can you please help me to solve this issue and provide me with several deb test packages that I can test with my PC? Maybe it will help you to find and issue?

**Comment by dimadeush** [comment]
half year since this issue posted and no results. Do you have support for intel-microcode?

**Comment by whpenner** [comment]
@dimadeush I need to have more details to be able to help.  I have no other reports similar to yours.  I have read through what you have posted at the links above.  As far as folks running the CPU that you have (cpu family/model/stepping : 6/158/13) and the latest microcode updates (microcode update revision ID 0xEA), I'm not aware of any issues.

First of all, there may be multiple firmware items being loaded when you are trying to load the new firmware in your system.  We should start from there.   

Start by testing just the cpu microcode update.  Go to the microcode update github site and pull down the microcode for your system (https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/tree/main/intel-ucode/06-9e-0d).  For the current versions of Ubuntu, the file is in /lib/firmware/intel-ucode and for your system, it is named 06-9e-0d.  First rename the existing microcode update so you can restore the file later, in case the new microcode update isn't working.  Copy the file downloaded from github to this directory.  Then reboot.  If the system boots, the 'black screen' issue is probably not related to the CPU microcode.

If you get a black screen at that point, reboot and set 'dis_ucode_ldr' in grub.  You can then go back to the firmware directory, delete the new file and restore the original file.

Let me know if you are able to boot the system with just the cpu microcode updated.

**Comment by dimadeush** [comment]
@whpenner As I can see mentioned above file related to the latest intel microcode ( microcode-20210608 Release ). I already tested it using ubuntu update manager and after updating to the latest intel microcode I still can't boot system. So after  'dis_ucode_ldr' in grub I'm able to boot, delete new intel microcode and revert back 20191115.1ubuntu3.
I kindly ask you to check what were changed after 20191115.1ubuntu3 and maybe you will find an issue. 
Please please please help, I want to use my new laptop in order to work with linux without dancing with intel microcode.

With hope
Thanks in Advance

**Comment by dimadeush** [comment]
@whpenner how much cost a fix for that?  I want to help to find an issue and will wait for fix. More then half a year but still can't use my notebook for working with Linux Ubuntu without "dancing" with intel microcode.

**Comment by dimadeush** [comment]
@esyr-rh @mcu-administrator  Please help

**Comment by dimadeush** [comment]
do we have any news? is intel-microcode project still alive?

**Comment by dimadeush** [comment]
Hello
Asus delivered new BIOS update for the laptop - " Version 309 2021/12/06" (https://rog.asus.com/laptops/rog-flow/rog-g703-series/helpdesk_bios) with description "Optimize system performance". After upgrading BIOS problem solved and I can use laptop with the latest intel microcode.
It a SHAME for the ASUS ROG due to fix was delivered AFTER 2 years! Also there is no info about fix, just description "Optimize system performance". Unfortunately premium ASUS ROG laptop with bad quality support.

**Comment by dimadeush** [comment]
Hello
I have latest Linux Mint version with intel microcode 3.20210608.0ubuntu0.20.04.1 and today I got updates with intel-microcode (3.20220510.0ubuntu0.20.04.1). After updating I'm again have the same issue as in the past - black screen and nothing working, helps only change boot option "quite splash" to "dis_ucode_ldr". Please stop updating intel microcode without proper testing or a lot users with Asus ROG laptop will have the same black screen.
Thanks in Advance
