### ISSUE TITLE
06-8c-01: Missing microcode updates

### ISSUE THREAD

**Issue by paulmenzel** [intel/Intel-Linux-Processor-Microcode-Data-Files#51]
A user is reporting random crashes with a Dell XPS 13 9310 2-in-1 using Debian sid/unstable tested with Linux kernel up to 5.10.9-1.

To rule out processor bugs, when are the microcode updates going to be available? The release notes for the latest release 20201118 say the updates were removed:

> *   Removed TGL/06-8c-01/80 due to functional issues with some OEM platforms.

First entry in `/proc/cpuinfo`:

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 140
model name	: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
stepping	: 1
microcode	: 0x60
cpu MHz		: 1187.117
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 27
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_go
od nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx 
f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invp
cid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_win
dow hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple pml ept_mode_based_exec tsc_scaling
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs
bogomips	: 4838.40
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

[…]
```

**Comment by crawfxrd** [comment]
Latest release, microcode-20210608, adds TGL back.

**Comment by paulmenzel** [comment]
The latest Dell system firmware update is [version 2.2.1](https://www.dell.com/support/home/de-de/drivers/driversdetails?driverid=w5k28&oscode=wt64a&productcode=xps-13-9310-2-in-1-laptop):

> ## Fehlerkorrekturen und Verbesserungen
> ### Korrekturen:
> - Behebung des Problems, bei dem beim Schließen der Systemabdeckung nach dem Neustart des Systems keine Audioausgabe am externen Monitor erfolgt
> 
> ### Verbesserungen:
> - Update der Intel Management Engine zur Verbesserung der Thunderbolt-Konnektivität
> - Update der Firmware der Embedded Controller Engine zur Verbesserung der Akkulaufzeit
> - Sekundäre Funktionstaste hinzugefügt, die Fn + Links als Home und Fn + Rechts als Ende ist

I am going to check in the next weeks, what microcode updates are shipped with that, and see if Debian is going to package the new microcode updates soon.

**Comment by esyr-rh** [comment]
It seems that it is available now: http://http.us.debian.org/debian/pool/non-free/i/intel-microcode/intel-microcode_3.20210608.1_amd64.deb
