### ISSUE TITLE
Downgrade from ucode rev 0xc6

### ISSUE THREAD

**Issue by thorncorona** [intel/Intel-Linux-Processor-Microcode-Data-Files#52]
How do I downgrade my uCode for my i7-9750h so that I can undervolt my CPU again?

**Comment by iamahuman** [comment]
Microcode is reset on shutdown/reboot, and thus must be applied every time the machine (re)boots. This process is handled by your OS/BIOS. Consult your software distribution's instructions on microcode management.

**Comment by iamahuman** [comment]
If microcode package for lower version is not available, try searching for older revision from this repository's releases and copying the appropriate microcode file to /lib/firmware/intel-ucode.

**Comment by Rpwelsome** [comment]
NO I want the updated version

**Comment by thorncorona** [comment]
Thanks for the info @iamahuman. I'll try it out.
