### ISSUE TITLE
Why are there sometimes `_DUPLICATE` microcode files?

### ISSUE THREAD

**Issue by nicholasbishop** [intel/Intel-Linux-Processor-Microcode-Data-Files#68]
Most of the microcode files are named in `family-model-stepping` format as described in the readme. Recently however (starting in commit 752cd0a7f09244f9336b7bb6d570e780e502c290) some files have been introduced with the format `family-model-stepping_DUPLICATE`. I'm curious why these files exist?

**Comment by JonathonHall-Purism** [comment]
I noticed this for 06-8e-09, in that case it looks like they have different platform support (`c0` vs. `10`)
