### ISSUE TITLE
What does the `_DUPLICATE` suffix mean?

### ISSUE THREAD

**Issue by paulmenzel** [intel/Intel-Linux-Processor-Microcode-Data-Files#69]
I couldn’t find an explanation, what the `_DUPLICATE` suffix mean.

**Comment by whpenner** [comment]
You can ignore those files.  They contain the previous MCU revision and will be removed in the future.

**Comment by paulmenzel** [comment]
Thank you fore the explanation. In my opinion they could be left in the archive, and just a section to the `README` could be added.

**Comment by paulmenzel** [comment]
Indeed, removed in commit https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/ece0d294a29a1375397941a4e6f2f7217910bc89. Too bad, Intel does use best practices and reference issues in commit messages with

> Closes: https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/ece0d294a29a1375397941a4e6f2f7217910bc89

so GitHub can automatically close the issue.
