### ISSUE TITLE
Any timeframe on when 0x206d7 microcode will be updated? 

### ISSUE THREAD

**Issue by Dansthunder** [intel/Intel-Linux-Processor-Microcode-Data-Files#7]
Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz (fam: 06, model: 2d, stepping: 07) is listed as TBA on Intel's PDF: https://www.intel.com/content/dam/www/public/us/en/documents/corporate-information/SA00233-microcode-update-guidance_05132019.pdf   It's been another month, and still nothing.

**Comment by iosifpeterfi** [comment]
I am also curious if there is a timeline for this.

**Comment by hbfs** [comment]
+1

**Comment by mrtwister76** [comment]
+1

**Comment by hbfs** [comment]
unofficial here https://github.com/platomav/CPUMicrocodes/blob/master/Intel/cpu206D7_plat6D_ver00000718_2019-05-21_PRD_62492450.bin

possibly they released it to a vendor and fortunately someone uploaded it

**Comment by Dansthunder** [comment]
Converted to .dat, and it loads up on one of my ancient Centos 6.10 boxes.   
microcode: CPU0 sig=0x206d7, pf=0x1, revision=0x710
microcode: CPU0 updated to revision 0x718, date = 2019-05-21

I'll mod up some bios images and load them up.  I appreciate the dump!

**Comment by hotaru2k3** [comment]
it's working fine for me. I just installed [intel-ucode-platomav-git from AUR](https://aur.archlinux.org/packages/intel-ucode-platomav-git/) on my Arch systems, and this is what I'm seeing:

```
$ grep microcode /proc/cpuinfo | uniq
microcode	: 0x718
$ grep md_clear /proc/cpuinfo | uniq
flags	: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
```

**Comment by mcu-administrator** [comment]
This microcode update has now been posted.  [https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20190618](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20190618)

**Comment by karakarga70** [comment]
61F is available for you inside DB 115.

**Comment by craig** [comment]
FYI: https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00233.html links a PDF, but does not reflect the updated microcode yet.

**Comment by mcu-administrator** [comment]
@craig Updated PDF posted on Aug 31, 2019 at the same link.
