### ISSUE TITLE
uCode for Voltage issue

### ISSUE THREAD

**Issue by ptr1337** [intel/Intel-Linux-Processor-Microcode-Data-Files#78]
Hi,

Since Linux is able to load the microcode on its own, would it be possible that the recent microcode gets also published here, to protect the Linux users simply via microcode early/pre loading?

**Comment by bunder2015** [comment]
I've been curious about this as well, as I have a laptop that might never get a bios update for this...  granted mobile chips supposedly aren't affected, but it would still be nice to have an update for peace of mind.

**Comment by lindem** [comment]
I will be checking here and at the board manufacturer website regularly, and to be honest am not at peace of mind until I have that update. My processor is on the list and it is kind of a letdown not finding this anywhere as early as possible.

**Comment by ptr1337** [comment]
> I will be checking here and at the board manufacturer website regularly, and to be honest am not at peace of mind until I have that update. My processor is on the list and it is kind of a letdown not finding this anywhere as early as possible.
> 
> EDIT: for other people also looking for this update:
> 
> there is also http://ftp.ubuntu.com/ubuntu/pool/main/i/intel-microcode/ where supposedly the microcode should be published, but it is not there either (latest is june 2024). Regularly checking there as well...

Personally, I do not have any Intel devices, but I would like to ship a fix as soon as possible in my distribution and would also bring this forward to other maintainers.
The Microcode of ubuntu, is the same which you can find here in the releases.

**Comment by KurtFuchs** [comment]
In their Post at the [Intel Community](https://community.intel.com/t5/Processors/Microcode-0x129-Update-for-Intel-Core-13th-and-14th-Gen-Desktop/m-p/1622129) Forums, they say this patch will not be available through OS updates.... So i hope they at-least release the microcode to this Repository, so that it can be updated in coreboot. Bad experience over all.

**Comment by ptr1337** [comment]
> In their Post at the [Intel Community](https://community.intel.com/t5/Processors/Microcode-0x129-Update-for-Intel-Core-13th-and-14th-Gen-Desktop/m-p/1622129) Forums, they say this patch will not be available through OS updates.... So i hope they at-least release the microcode to this Repository, so that it can be updated in coreboot. Bad experience over all.

I think this applies only to windows, but we will see. The Windows ucode updates are very rare.

**Comment by whpenner** [comment]
Hi folks, let me add some clarity.  The microcode update (MCU) for the 13th and 14th Generation Intel desktop processors that was released last week (MCU Revision ID 129) is not effective for the Instability issue when loaded from the OS.  To be effective, the MCU will need to be loaded from BIOS.  This is the same for all operating systems; Windows, Linux, virtualization environments, or anything else where the MCU is loaded after BIOS done.  This is also why the MCU was not posted to this repository last week since we did not want to confuse people into believing that systems were mitigated for this issue by loading the MCU from the OS or virtualization environment.

**Comment by ptr1337** [comment]
Perfectly, thanks for the explanation. Then Ill close here.

**Comment by n-huber** [comment]
> This is the same for all operating systems; Windows, Linux, virtualization environments, or anything else where the MCU is loaded after BIOS done. This is also why the MCU was not posted to this repository last week since we did not want to confuse people into believing that systems were mitigated for this issue by loading the MCU from the OS or virtualization environment.

Well, then Intel needs to create another repository or branch for BIOS use. This repository here is also used by coreboot.org, and the primary and quickest way to get MCUs shipped for Intel's customers using such firmware. It's not really hard to make that calculation: A few hours to publish the MCU on one hand vs. thousands more RMA cases on the other...

**Comment by felixsinger** [comment]
@whpenner Could you reconsider what you have written in your comment? Open source firmware projects are using this repository and by not publishing it they are excluded.

I understand you want to prevent confusion, but that's the wrong way to do it. In any case, the vendors need to release firmware updates and the customers need to get aware of them.

**Comment by whpenner** [comment]
@felixsinger Reconsidered :-)  See update for issue #81.

**Comment by QyInvoLing** [comment]
> Hi folks, let me add some clarity. The microcode update (MCU) for the 13th and 14th Generation Intel desktop processors that was released last week (MCU Revision ID 129) is not effective for the Instability issue when loaded from the OS. To be effective, the MCU will need to be loaded from BIOS. This is the same for all operating systems; Windows, Linux, virtualization environments, or anything else where the MCU is loaded after BIOS done. This is also why the MCU was not posted to this repository last week since we did not want to confuse people into believing that systems were mitigated for this issue by loading the MCU from the OS or virtualization environment.

Does manually modify the bios, replacing 0x104 microcode with 0x12b microcode work?

**Comment by whpenner** [comment]
The best answer I can give is maybe.  If you are right, and the MCU is Revision ID 0x104 for CPUID b0671, it would be a pre-production MCU.  I don't see any obvious issues in the errata, but a pre-production BIOS may be missing some updates.  As far as the instability issue, the changes in MCU 0x129 should be effective as long as the MCU is loaded using the FIT table.

There are some IFWI changes as well, but the limits applied by the MCU is the most important part.  Although it sounds like you may be familiar with the process of replacing the MCU, make sure to account for the larger size of MCU 0x12b over 0x104, if there are other MCUs in that BIOS or if there is other data after the MCU.
