### ISSUE TITLE
Missing 06-a5-03 update in IPU 2024.3 release?

### ISSUE THREAD

**Issue by stormi** [intel/Intel-Linux-Processor-Microcode-Data-Files#79]
I compared the release notes with the actual contents of the .tar.gz archive, and I see no changes for `06-a5-03` in the archive, despite it is mentioned in the release notes.

**Comment by stormi** [comment]
```
$ iucode_tool -L 06-a5-03 
microcode bundle 1: 06-a5-03
  001/001: sig 0x000a0653, pf_mask 0x22, 2023-07-16, rev 0x00fa, size 97280
```

Revision `0x00fa` when `0x00fc` is expected according to the release note.

**Comment by whpenner** [comment]
Good catch.  We will be posting the correct file shortly.

**Comment by jonathangray** [comment]
In future, please don't rewrite the history and retag.  Make a new release.  When checksums change, builds break.

**Comment by hmh** [comment]
Hmm, I second that. An 20240813v2, or 20240813a, or even 20240814 release would have been nice.  But now that many people already got the new branch-head, it is best if we carry on as is, or it will be twice the pain.

For a possible next time this is needed, please consider doing a "minor update incremental release", instead.

For the record, Debian (and likely Ubuntu) intel-microcode package tagged as 20240813 will be the corrected (current) release.  I won't tag it as 20240813a or 20240814 to not cause confusion when people compare version among distros.

**Comment by whpenner** [comment]
Thanks - I'll take that back to our folks who do the posting.
