### ISSUE TITLE
Create GitHub releases

### ISSUE THREAD

**Issue by bgilbert** [intel/Intel-Linux-Processor-Microcode-Data-Files#9]
When tagging a new microcode release, please consider [creating a GitHub release](https://help.github.com/en/articles/creating-releases) afterward.  This provides an easy way to browse release notes for older releases.  More importantly, it allows someone to watch "Releases only" in the GitHub repository and receive email when a new release is published.

Thanks!

**Comment by mcu-administrator** [comment]
@bgilbert Releases are currently disabled on the repository.  I'll check with our Github Org Admin to see if we can get that enabled.

**Comment by esyr-rh** [comment]
It seems that the issue still holds.
